version: '3'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
       # volumes:
        #    - ./data:/data/db
    api:
        image: node
        volumes:
            - ./:/usr/src/app
        ports:
            - "3000:3000"
        environment:
            - MONGO_DB_URI=mongodb://mongo:27017/work
        depends_on:
            - mongo
        command: bash -c "cd /usr/src/app && npm i && node index.js"

