version: '3'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
       # volumes:
        #    - ./data:/data/db
    api:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - mongo


